// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpwwmhvugihmhhymncdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwd3dtaHZ1Z2lobWhoeW1uY2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDk2MTUsImV4cCI6MjA2MzY4NTYxNX0.1Kv5CqWWCjVJxs4nxs42VuKxtbUzel4xvOKEk755DRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);